complete -c font-set -f -n '__fish_is_first_token' -a jetbrains   -d 'JetBrains Mono (default; ligatures)'
complete -c font-set -f -n '__fish_is_first_token' -a fira        -d 'FiraCode (ligatures)'
complete -c font-set -f -n '__fish_is_first_token' -a cascadia    -d 'Cascadia Code / CaskaydiaCove (ligatures)'
complete -c font-set -f -n '__fish_is_first_token' -a monaspace   -d 'GitHub Monaspace Neon (ligatures)'
complete -c font-set -f -n '__fish_is_first_token' -a iosevka     -d 'Iosevka (ligatures; narrow)'
complete -c font-set -f -n '__fish_is_first_token' -a hack        -d 'Hack (no ligatures; classic)'
complete -c font-set -f -n '__fish_is_first_token' -a meslo       -d 'MesloLGS (no ligatures; Powerlevel10k default)'
complete -c font-set -f -n '__fish_is_first_token' -a sauce       -d 'SauceCodePro / Source Code Pro (no ligatures)'
complete -c font-set -f -n '__fish_is_first_token' -a ubuntu      -d 'UbuntuMono (no ligatures)'
complete -c font-set -f -n '__fish_is_first_token' -a inconsolata -d 'Inconsolata (no ligatures)'
